services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/local/express/Dockerfile
    volumes:
      - /app/node_modules
      - /app/logs
      - /app/prisma
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: development
      PORT: ${PORT}
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      FORCE_COLOR: 1
    depends_on:
      - db
    networks:
      - bidding

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bidding

networks:
  bidding:
    driver: bridge

volumes:
  db-data:
